#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
i=0
while (( i < 10 ))
do

    if (( i!=8 ))
    then
	echo Best School
    else
	echo "Best School"
	echo "Hi"
    fi
    (( i++ ))
done
