#!/usr/bin/env bash
# This script displays "bad luck from china" in the 4th loop, "bad luck from japan" in the 9th loop, "bad luck from italy" in the 17th loop, and numbers for any other loop until the number 20

i=1
while (( i<=20  ))
do
    echo "$i"
    case $i in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
    esac
    (( i++ ))

done
