#!/usr/bin/env bash
# Script that displays hours from 0 to 12 and minutes from 1 to 59

h=0
while (( h<12 ))
do
    echo -n 'Hour: "$h"'
    m=1
    while (( m<=59 ))
    do
	echo "$m"
	(( m++ ))
    done
    (( h++ ))
done
